spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  liquibase:
    url: jdbc:postgresql://localhost:5432/test_db
    user: postgres
    password: postgres
    change-log: liquibase/db.changelog-master.yaml
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true